# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # test against latest update of each major Java version, as well as specific updates of LTS versions:
        java: [ 11.0.x, 11.0.3, 12, 13, 14 ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Docker Post-Maven steps
      run: make clean push
      #uses: docker/build-push-action@v1.1.0
      env:
        DOCKER_USERNAME: cricketeerone
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
